# Generated by Django 5.1.4 on 2025-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_model_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeoption',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
