# Generated by Django 5.1.4 on 2025-01-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sizeoption_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeoption',
            name='size_category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.sizecategory'),
            preserve_default=False,
        ),
    ]
