# Generated by Django 5.1.4 on 2025-01-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sizeoption_size_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeoption',
            name='size_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sizecategory'),
        ),
    ]
