# Generated by Django 5.1.4 on 2025-01-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sizeoption_size_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='size_category_id',
        ),
    ]
