# Generated by Django 5.1.4 on 2025-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_address_country_alter_address_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
