# Generated by Django 5.1.4 on 2025-01-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Stripe_charge_id',
            new_name='stripe_charge_id',
        ),
    ]
